### ISSUE TITLE
Excluding files doesn't work

### ISSUE THREAD

**Issue by idleberg** [electron/asar#180] opened 2019-06-02 10:25 UTC
Today I learned about the option to exclude folders and tried to make use of. However, none of the folders were excluded.

**Example:**

```sh
# Create structure from asar's README.md
$ mkdir app
$ mkdir app/x1
$ mkdir app/x2
$ mkdir app/y3
$ mkdir app/y3/x1
$ mkdir app/y3/z1
$ mkdir app/y3/z1/x2
$ mkdir app/y4

# Pack command from asar's README.md
$ asar pack app app.asar --unpack-dir "{x1,x2}"

# Listing file contents
$ asar list app.asar
/x1
/x2
/y3
/y3/x1
/y3/z1
/y3/z1/x2
/y4
```

The not sure whether `--unpack-dir` is supposed to work with files as well, but here's a second test with files.

```
$ mkdir app
$ touch app/x1
$ touch app/x2
$ mkdir app/y3
$ touch app/y3/x1
$ mkdir app/y3/z1
$ touch app/y3/z1/x2
$ touch app/y4

# Pack command from asar's README.md
$ asar pack app app.asar --unpack-dir "{x1,x2}"

# Listing file contents
$ asar list app.asar
/x1
/x2
/y3
/y3/x1
/y3/z1
/y3/z1/x2
/y4
```

My Setup:

```
System Version: macOS 10.14.5 (18F132)
Kernel Version: Darwin 18.6.0

node v12.2.0
nvm v0.34.0
asar v2.0.1
```

**Comment by idleberg** [comment] 2019-06-02 13:24
I looked into the source code and came across the `--is-pack` option. It seams to me that `--unpack-dir` only specifies whether a file is `pack` or `unpack` – for whatever that means. The extract command extracts all files, no matter if set to either.

I find the `asar` format interesting and would love to make use of it. It would be helpful if such things and their purpose were better documented.

**Comment by malept** [comment] 2019-06-02 16:31
Duplicate of #2

**Closed by malept** 2019-06-02 16:31 UTC

**Comment by idleberg** [comment] 2019-06-02 17:05
I don't understand how a _feature request_ is a duplicate of an _issue_ with the same feature. The feature has been implemented since the feature request was posted, but using the examples from the official documentation doesn't work. I was hoping to help or at least get some constructive feedback.

**Comment by malept** [comment] 2019-06-02 17:08
Excluding files from being listed in the ASAR archive is a feature that the `asar` module itself doesn't have yet. As you noted, it's different from `unpack` and `unpackDir`. There are several other issues that deal with "the docs for asar need help", so this one doesn't need to be open.
