### ISSUE TITLE
building with nodejs 8.2.1+ does not support asar packaging

### ISSUE THREAD

**Issue by macgyver13** [electron/asar#138] opened 2017-12-12 14:22 UTC
Followed instructions provided [here](https://electronjs.org/docs/development/build-instructions-osx) to build electron 1.8.2-beta2 using Xcode 9.1, node 8.2.1, macOS 10.13.  After successfully packaging using electron-packager the application will fail on launch if asar is used.  I suspect this [change](https://github.com/nodejs/node/commit/c83d9bbffbe879f9d67f72c14213139616ec4302) in lib/module.js is causing the issue.  Packaging the app without asar works fine.

**Summary**
lib\module.js:updateChildren(parent, this, false) appears to work fine when asar is not used.

Added a console.log message to reset-search-paths.js for github sourced binary and it produced the following log:
```
...app/Contents/Resources/app.asar/app.js parent: function Module(id, parent) {
  this.id = id;
  this.exports = {};
  this.parent = parent;
  if (parent && parent.children) {
    parent.children.push(this);
  }

  this.filename = null;
  this.loaded = false;
  this.children = [];
} main: true
electron-squirrel-startup parent: [object Object] main: false
path parent: [object Object] main: false
child_process parent: [object Object] main: false
debug parent: [object Object] main: false
```

Added a console.log message to reset-search-paths.js for built binary and it produced the following log:
```
...app/Contents/Resources/app.asar/app.js parent: function Module(id, parent) {
  this.id = id;
  this.exports = {};
  this.parent = parent;
  updateChildren(parent, this, false);
  this.filename = null;
  this.loaded = false;
  this.children = [];
} main: true
electron-squirrel-startup parent: [object Object] main: false
path parent: [object Object] main: false
child_process parent: [object Object] main: false
debug parent: [object Object] main: false
```

<img width="324" alt="error" src="https://user-images.githubusercontent.com/4712150/33888840-3d1ed59e-df1c-11e7-9a48-6faa7ef4b8fc.png">

**Comment by malept** [comment] 2020-03-31 00:32
No one else seems to be having this issue, so I'm closing it. If other people are indeed having this issue, please provide a *minimal* testcase so that others can reproduce the behavior you're experiencing.

**Closed by malept** 2020-03-31 00:32 UTC
