### ISSUE TITLE
ASAR throws an exception when it extract 【Attempt to write outside buffer bounds】

### ISSUE THREAD

**Issue by seanhepps** [electron/asar#214] opened 2021-03-26 06:59 UTC
command：asar extract app.asar ./
then:
internal/buffer.js:47
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:47:11)
    at Buffer.readUInt32LE (internal/buffer.js:105:5)
    at Pickle.getPayloadSize (/usr/local/lib/node_modules/asar/node_modules/chromium-pickle-js/lib/pickle.js:192:24)
    at new PickleIterator (/usr/local/lib/node_modules/asar/node_modules/chromium-pickle-js/lib/pickle.js:27:28)
    at Pickle.createIterator (/usr/local/lib/node_modules/asar/node_modules/chromium-pickle-js/lib/pickle.js:144:12)
    at Object.module.exports.readArchiveHeaderSync (/usr/local/lib/node_modules/asar/lib/disk.js:68:23)
    at Object.module.exports.readFilesystemSync (/usr/local/lib/node_modules/asar/lib/disk.js:84:25)
    at Object.module.exports.extractAll (/usr/local/lib/node_modules/asar/lib/asar.js:170:27)
    at Command.<anonymous> (/usr/local/lib/node_modules/asar/bin/asar.js:72:10)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/asar/node_modules/commander/index.js:413:31)

asar version:v3.0.3

The window os is same.
please help me ,how to successfully extract。
Thank you.

**Comment by malept** [comment] 2021-05-13 05:37
Duplicate of #183

**Closed by malept** 2021-05-13 05:37 UTC
Labels: duplicate
