### ISSUE TITLE
dynamic import not working inside asar

### ISSUE THREAD

**Issue by StreetStrider** [electron/asar#249] opened 2022-11-28 19:39 UTC
I need to use esm only package (lowdb). To do this I use dynamic import to workaround electron's cjs-only. It works fine in dev build. After bundling app to asar this fails, because process cannot resolve import from lowdb. lowdb package featuring exports maps, so it might be related to the fact that required module file differs from import uri (resolved via export map).

**Comment by smhdfdl** [comment] 2023-02-17 17:32
Also encountered this today. The specific line of code that fails only in the asar is...
```
    const { default: got } = await import('got')
```

**Comment by GitMurf** [comment] 2023-05-06 15:25
Check this out and the "Things that were fixed" section. This is a solution for ESM imports but also fixes I believe the problems with dynamic imports in asar. https://github.com/electron/electron/pull/37535

**Comment by GitMurf** [comment] 2023-05-06 15:29
![image](https://user-images.githubusercontent.com/64155612/236633309-bf9c1e69-5f47-4793-9137-7e7240eece18.png)

**Comment by glowtape** [comment] 2023-06-12 08:11
How did you solve the issue with nested dependencies? I've tried an artifact of the pull request you referred, and while a lot of ESM things now work, it seems like it doesn't respect the exports section of the package.json files in the ASAR.

**Comment by erikian** [comment] 2023-10-16 16:17
Should be fixed by https://github.com/electron/electron/pull/40221. I'm closing this for now since the issue is not on `@electron/asar`'s side.

**Closed by erikian** 2023-10-16 16:17 UTC
